sudo: false
language: python
python:
- 2.7
- 3.5
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  distributions: dists
  password:
    secure: fiaov4FZwM7eYE3IVN4Dxn+8M3kXgQSpyma9BJoTEHozOu8BLiWrRRdG+4d41DxAT5/42lt3FFzqX6lHb+5irzKC1G2g8pPMKFqPBFCrLR4BLKLoo2hygm6AXSIDXKVm/VfaHm4EQM1oRifZi11zMt6xhHX7vYZh8rONlNZv2m8nH89OTLnlszCwNEX8bolmhYWRsRpevlmbJnrehyad1FF7SXf2Bd4kU5Ap2gFTqtLAtQ9OSlstJiZGFk74FbWBPZuPWv/lzrVIwhrLx+UTALx6f9bYGn0oQzJd5z27yqmujlkWA0Xv5vfFhek7DAkmFuXz7nzw1xdU1HKXK9RhFHlah++SVKQUj95esJ3tF7zzu4qYQ89KucUa5wVU3m/uVr/lAiDSVlWlpdDFJOEPkGRNTnzKpNJF4AKAegMr/AsGdg+WHXbl2GlhgO1iQfWnIF1BevEAqa1cEhnVDUzt21xU4eXyc8ivH5Mxlt3Nxv3rmYTIWtKv5NJ12pLHv6ZX49dmIC9rhP6kX1MDftzS5qnXguheVOFFHwbzt9NsQmqJMofkpcSMsfSuL8EEh/cQhcC9ceuLXd2jQjHpyJ518oM+vCz+Vyv41zdGs4uS3fF0EjNKWJ5SG8VCjra4N8+Wu4xJE4sY9byt3pBWP27wW6nFwNBsdC+zVLcBl1tSEIs=
env:
  secure: YKaqoYmjvrR93lVqd0YLNtygDZqfEJ/Ci3MKY1ya/A1Gk/zY7ySMd2JdYUl76BkyV6eb/+33zg0bGoI9tiGf/2WativmXfAIE4q0WCSzVWhy3aA25zPGMoOrCZlamHsHVese12rmzsJ+Xy04DHELxqClae7H3Ej95j2Kt3IEZoPhe8cAX2AmzUv9oN1hsrlAJYDEFUaa3LPakScxQuj+5P2mRTfui1diuJrC9W/JKQuite8LNJtea/jDs15g2fd42Ylim0cGDlrrjEvw9C9EvLO7AxDoxiOGUEnuyPOBWlxRuNeqbt/luv5rOL/eHa3qyV6i4B7aPutKTzqkx+l5jpVlD8wxePZ0mMn1dj01GrUROiDhEh4vrXx+4E0Fhm0L7nEQN8EKIJhxtqLUfEYWRHhn8nSUjoXq18uisP7ch35JelvSQ4teT5dYc0hcHTbeNKW0CATvw2/12eWcmF1d3EzY1LIsc4nvPubZ2bhw9m+DUBY+Slr0Vt7Boyw2f9ad5ybHvBqFeYVgHQ+X0tffnZOX4c9GqTz7FQAziXQ/XlZo5fa/6qfUzuvQ5IqliTXXiGrnerMBCfLgxJ28FfgtySfb/0Ho8BTyt5CAaHmBtAegCI6GqgT9VexUEu+WysV9oY7nZHx1rxrqxHc2deoA1ZKwQGe4m6uRll0gHLvcwVs=
